name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Check answers
      run: |
        if [[ $(cd "Day 1" && python "Part 1.py") -ne 1466 ]]; then exit 1; fi;
        if [[ $(cd "Day 1" && python "Part 2.py") -ne 1491 ]]; then exit 1; fi;
        if [[ $(cd "Day 2" && python "Part 1.py") -ne 2019945 ]]; then exit 1; fi;
        if [[ $(cd "Day 2" && python "Part 2.py") -ne 1599311480 ]]; then exit 1; fi;
        if [[ $(cd "Day 3" && python "Part 1.py") -ne 1307354 ]]; then exit 1; fi;
        if [[ $(cd "Day 3" && python "Part 2.py") -ne 482500 ]]; then exit 1; fi;
        if [[ $(cd "Day 4" && python "Part 1.py") -ne 71708 ]]; then exit 1; fi;
        if [[ $(cd "Day 4" && python "Part 2.py") -ne 34726 ]]; then exit 1; fi;
  